# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 08:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=200, verbose_name='TODO Task')),
                ('todo_start_date', models.DateField(default=datetime.datetime(2018, 1, 1, 8, 28, 48, 381679, tzinfo=utc), verbose_name='Start Date')),
                ('todo_due_date', models.DateField(default=datetime.datetime(2018, 1, 11, 8, 28, 48, 381729, tzinfo=utc), verbose_name='Due Date')),
                ('todo_status', models.BooleanField(default=False)),
            ],
        ),
    ]
