# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_due_date',
            field=models.DateField(default=datetime.datetime(2018, 1, 11, 8, 30, 2, 15245, tzinfo=utc), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_start_date',
            field=models.DateField(default=datetime.datetime(2018, 1, 1, 8, 30, 2, 15191, tzinfo=utc), verbose_name='Start Date'),
        ),
    ]
