# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 08:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20180101_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_due_date',
            field=models.DateField(default=datetime.datetime(2018, 1, 11, 8, 31, 55, 681890, tzinfo=utc), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
    ]
